# Auto-generated by scripts/00_project_setup.R
suppressPackageStartupMessages({
  library(ggplot2)
})

# Global ggplot theme
Kelp_theme <- function(base_size = 11) {
  ggplot2::theme_minimal(base_size = base_size) +
    ggplot2::theme(
      panel.grid.minor = ggplot2::element_blank(),
      plot.title.position = 'plot',
      legend.position = 'right',
      strip.text = ggplot2::element_text(face = 'bold')
    )
}

# Named colour palette (edit as you iterate)
kelp_palette <- c(
  kelp_green = '#2E7D32',
  kelp_teal  = '#00796B',
  kelp_blue  = '#1565C0',
  kelp_amber = '#FF8F00',
  kelp_red   = '#C62828',
  kelp_grey  = '#455A64'
)

