# Project:     SPM Analysis - Impact on kelp spore motility
# Scripts:     00_project_setup.R
# Author:      Marianne Glascott
# Affiliation: School of Life Sciences, University of Sussex
# Date:        2026_February_10
# Version:     1.0
# ==============================================================================
# Goal: Initialize a fully reproducible R project for Manuscript 4 (SPM & zoospore motility)
# Requirements:
# - Initialize renv
# - Create standard folder structure
# - Define global ggplot theme (Kelp_theme)
# - Define named colour palette (kelp_palette)
# - Define helper functions: save_plot(), save_table(), log_message()
# Outputs to disk:
# - renv.lock (via renv)
# - folders
# - outputs/setup_log.txt
# Do not load data. Do not fit models.

suppressPackageStartupMessages({
  if (!requireNamespace("here", quietly = TRUE)) install.packages("here")
})
library(here)

# ---------- Paths ----------
dir_outputs <- here::here("outputs")
dir_scripts <- here::here("scripts")
dir_data_raw <- here::here("data_raw")
dir_data_processed <- here::here("data_processed")
dir_figures <- here::here("figures")
dir_tables <- here::here("tables")
dir_models <- here::here("models")
dir_logs <- here::here("logs")
dir_R <- here::here("R")

# ---------- Create folders ----------
dirs_to_create <- c(
  dir_outputs, dir_scripts, dir_data_raw, dir_data_processed,
  dir_figures, dir_tables, dir_models, dir_logs, dir_R
)
for (d in dirs_to_create) {
  if (!dir.exists(d)) dir.create(d, recursive = TRUE, showWarnings = FALSE)
}

# ---------- Logging helper (inline, then written to R/helpers.R) ----------
setup_log_file <- file.path(dir_outputs, "setup_log.txt")

log_message_inline <- function(msg, log_file = setup_log_file) {
  ts <- format(Sys.time(), "%Y-%m-%d %H:%M:%S")
  line <- paste0("[", ts, "] ", msg)
  cat(line, "\n")
  dir.create(dirname(log_file), recursive = TRUE, showWarnings = FALSE)
  cat(line, "\n", file = log_file, append = TRUE)
}

log_message_inline("Starting 00_project_setup.R")
log_message_inline(paste0("Project root (here::here()): ", here::here(".")))

# ---------- Initialize renv ----------
if (!requireNamespace("renv", quietly = TRUE)) {
  log_message_inline("renv not installed; installing from CRAN...")
  install.packages("renv")
}

# Only init if not already present
if (!file.exists(here::here("renv.lock"))) {
  log_message_inline("Initializing renv (bare = TRUE)...")
  renv::init(bare = TRUE)
  log_message_inline("renv initialized; renv.lock should now exist.")
} else {
  log_message_inline("renv.lock already exists; skipping renv::init().")
}

# Ensure key packages recorded (but don't force-install a long list)
pkgs_min <- c("ggplot2", "readr", "dplyr")
missing_min <- pkgs_min[!vapply(pkgs_min, requireNamespace, logical(1), quietly = TRUE)]
if (length(missing_min) > 0) {
  log_message_inline(paste0(
    "Some common packages are missing: ", paste(missing_min, collapse = ", "),
    ". You can install via renv::install(c(...)) later."
  ))
}

# ---------- Write style + helpers to R/ ----------
style_file <- file.path(dir_R, "kelp_style.R")
helpers_file <- file.path(dir_R, "helpers.R")

style_contents <- c(
  "# Auto-generated by scripts/00_project_setup.R",
  "suppressPackageStartupMessages({",
  "  library(ggplot2)",
  "})",
  "",
  "# Global ggplot theme",
  "Kelp_theme <- function(base_size = 11) {",
  "  ggplot2::theme_minimal(base_size = base_size) +",
  "    ggplot2::theme(",
  "      panel.grid.minor = ggplot2::element_blank(),",
  "      plot.title.position = 'plot',",
  "      legend.position = 'right',",
  "      strip.text = ggplot2::element_text(face = 'bold')",
  "    )",
  "}",
  "",
  "# Named colour palette (edit freely as you iterate)",
  "kelp_palette <- c(",
  "  kelp_green = '#2E7D32',",
  "  kelp_teal  = '#00796B',",
  "  kelp_blue  = '#1565C0',",
  "  kelp_amber = '#FF8F00',",
  "  kelp_red   = '#C62828',",
  "  kelp_grey  = '#455A64'",
  ")",
  ""
)

helpers_contents <- c(
  "# Auto-generated by scripts/00_project_setup.R",
  "suppressPackageStartupMessages({",
  "  library(here)",
  "  library(ggplot2)",
  "  library(readr)",
  "})",
  "",
  "# Log messages to a file (default: outputs/run_log.txt)",
  "log_message <- function(msg, log_file = here::here('outputs', 'run_log.txt')) {",
  "  ts <- format(Sys.time(), '%Y-%m-%d %H:%M:%S')",
  "  line <- paste0('[', ts, '] ', msg)",
  "  cat(line, '\\n')",
  "  dir.create(dirname(log_file), recursive = TRUE, showWarnings = FALSE)",
  "  cat(line, '\\n', file = log_file, append = TRUE)",
  "  invisible(line)",
  "}",
  "",
  "# Save a ggplot with informative defaults; always writes to disk",
  "save_plot <- function(p, filename, width = 7, height = 5, dpi = 300, dir = here::here('figures')) {",
  "  dir.create(dir, recursive = TRUE, showWarnings = FALSE)",
  "  out <- file.path(dir, filename)",
  "  ggplot2::ggsave(filename = out, plot = p, width = width, height = height, dpi = dpi, units = 'in')",
  "  log_message(paste0('Saved plot: ', out))",
  "  return(out)",
  "}",
  "",
  "# Save a table to disk; supports csv or tsv by extension",
  "save_table <- function(df, filename, dir = here::here('tables')) {",
  "  dir.create(dir, recursive = TRUE, showWarnings = FALSE)",
  "  out <- file.path(dir, filename)",
  "  ext <- tolower(tools::file_ext(out))",
  "  if (ext == 'csv') {",
  "    readr::write_csv(df, out)",
  "  } else if (ext == 'tsv') {",
  "    readr::write_tsv(df, out)",
  "  } else {",
  "    # fallback to csv if unknown",
  "    out <- paste0(out, '.csv')",
  "    readr::write_csv(df, out)",
  "  }",
  "  log_message(paste0('Saved table: ', out))",
  "  return(out)",
  "}",
  ""
)

writeLines(style_contents, con = style_file)
log_message_inline(paste0("Wrote style file: ", style_file))

writeLines(helpers_contents, con = helpers_file)
log_message_inline(paste0("Wrote helpers file: ", helpers_file))

log_message_inline("00_project_setup.R complete.")
