# Auto-generated by scripts/00_project_setup.R
suppressPackageStartupMessages({
  library(here)
  library(ggplot2)
  library(readr)
})

# Log messages to a file (default: outputs/run_log.txt)
log_message <- function(msg, log_file = here::here('outputs', 'run_log.txt')) {
  ts <- format(Sys.time(), '%Y-%m-%d %H:%M:%S')
  line <- paste0('[', ts, '] ', msg)
  cat(line, '\n')
  dir.create(dirname(log_file), recursive = TRUE, showWarnings = FALSE)
  cat(line, '\n', file = log_file, append = TRUE)
  invisible(line)
}

# Save a ggplot to disk
save_plot <- function(p, filename, width = 7, height = 5, dpi = 300, dir = here::here('figures')) {
  dir.create(dir, recursive = TRUE, showWarnings = FALSE)
  out <- file.path(dir, filename)
  ggplot2::ggsave(filename = out, plot = p, width = width, height = height, dpi = dpi, units = 'in')
  log_message(paste0('Saved plot: ', out))
  out
}

# Save a table to disk (csv/tsv by extension; otherwise .csv fallback)
save_table <- function(df, filename, dir = here::here('tables')) {
  dir.create(dir, recursive = TRUE, showWarnings = FALSE)
  out <- file.path(dir, filename)
  ext <- tolower(tools::file_ext(out))
  if (ext == 'csv') {
    readr::write_csv(df, out)
  } else if (ext == 'tsv') {
    readr::write_tsv(df, out)
  } else {
    out <- paste0(out, '.csv')
    readr::write_csv(df, out)
  }
  log_message(paste0('Saved table: ', out))
  out
}

